name: Update JSON File from Google Drive

on:
  schedule:
    - cron: "*/3 * * * *"  # Runs every 3 minutes
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures full commit history for rebase

    - name: Fetch updated JSON from Google Drive
      run: |
        FILE_ID="1jF_li2ZvXB3lD4HiqFsp-0Mh5Frb_Hb5"
        FILENAME="data/drawings_data.json"
        
        wget --no-check-certificate "https://drive.google.com/uc?export=download&id=$FILE_ID" -O $FILENAME || {
          echo "❌ Error: Failed to download JSON file!"
          exit 1
        }

    - name: Verify JSON file exists
      run: |
        if [ ! -s data/drawings_data.json ]; then
          echo "❌ Error: JSON file not downloaded or empty!"
          exit 1
        fi
        echo "✅ JSON file successfully downloaded."

    - name: Verify JSON file format
      run: |
        if jq . data/drawings_data.json > /dev/null 2>&1; then
          echo "✅ JSON file is valid."
        else
          echo "❌ Error: JSON file is not valid JSON format!"
          exit 1
        fi

    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"

    - name: Pull latest changes from GitHub
      run: |
        git pull --rebase --autostash origin main || echo "⚠ No changes to pull"

    - name: Commit and push if changed
      run: |
        git add data/drawings_data.json
        git commit -m "Updated JSON - $(date +'%Y-%m-%d %H:%M:%S')" || exit 0

        # ✅ Merge strategy to prevent conflicts
        git pull --rebase origin main || git merge --strategy-option=ours origin/main

        # ✅ Push changes to main
        git push origin main || echo "⚠ No changes to push"
