name: Update Drawings JSON

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch updated JSON from Google Drive
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=YOUR_FILE_ID" -o data/drawings_data.json

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/drawings_data.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update drawings JSON"
          git push
