name: Update Drawings JSON

on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch updated JSON from Google Drive
        run: |
          FILE_ID="1fru8p2v4eEr_Bu7Tsr2_f_objKC7lTWZ"
          FILENAME="data/drawings_data.json"
          wget --no-check-certificate "https://docs.google.com/uc?export=download&id=$1fru8p2v4eEr_Bu7Tsr2_f_objKC7lTWZ" -O $FILENAME

      - name: Verify JSON file exists
        run: |
          if [[ ! -f data/drawings_data.json ]]; then
            echo "❌ Error: JSON file not found!"
            exit 1
          fi
          echo "✅ JSON file successfully downloaded."

      - name: Verify JSON file format
        run: |
          if jq empty data/drawings_data.json; then
            echo "✅ JSON file is valid."
          else
            echo "❌ Error: JSON file is not valid!"
            exit 1
          fi

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/drawings_data.json
          if git diff --staged --quiet; then
            echo "🟢 No changes detected, skipping commit."
            exit 0
          fi
          git commit -m "Auto-update drawings JSON"
          git push
